### ISSUE TITLE
Add typescript typings

### ISSUE THREAD

**Issue by szechyjs** [sebastien-p/angular-release-name-generator#3]

**Comment by sebastien-p** [comment]
Hello, https://github.com/sebastien-p/angular-release-name-generator/releases/tag/1.2.1 ;)

Interested in knowing how you use this toy project...

**Comment by szechyjs** [comment]
Thanks, although I get NaN results because of the use of `version: number`. A semver like `1.2.3` is not a valid number. I originally typed everything as a string and it worked as expected.

**Comment by szechyjs** [comment]
> Interested in knowing how you use this toy project...

I'm working it into a gulp script to auto version a project.

**Comment by sebastien-p** [comment]
https://github.com/sebastien-p/angular-release-name-generator/blob/master/lib.js#L3
https://github.com/sebastien-p/angular-release-name-generator/blob/master/lib.js#L27
https://github.com/sebastien-p/angular-release-name-generator/blob/master/lib.js#L45

As you can see, `version` should be a number (*major* part of semver), `version: number` in the interface declaration is just a hint and doesn't do any "casting" whatsoever so I don't see why you would get `NaN`. Do you have more informations about this?

**Comment by szechyjs** [comment]
I was passing a full semver string like `1.2.3` as the version parameter. 

Ideally it would be nice to just have an exported function that only generates the codename.

**Comment by sebastien-p** [comment]
Passing `null` as `version` currently allows to skip fetching the current Angular version. Now we could also do something similar to skip fetching the associated gif I guess.

**Comment by sebastien-p** [comment]
https://github.com/sebastien-p/angular-release-name-generator/releases/tag/1.3.1
https://github.com/sebastien-p/angular-release-name-generator/blob/master/README.md#lib

Enjoy

**Comment by szechyjs** [comment]
Thanks! 🍻
